### ISSUE TITLE
DAY 2 SOLUTION

### ISSUE THREAD

**Issue by Lemiz1** [motoko-bootcamp/education#1]
So I pasted the code in Motoko playground but it keeps throwing me errors. The approach of the switch case is nice, however, the problem happens with the Filter function. Since `func filter<A>(xs : [A], f : A -> Bool) : [A]` doesn't have `?` output so it seems doesn't work. Therefore, I suggest using
```
 public func duplicated_character(t : Text) : async Text{
        for (character in t.chars()){
            if(Text.contains(t, #text(Char.toText(character)))){
                return(Text.fromChar(character));
            };
        };
        return(t);

    };
```
For a more simple approach and easy to understand. Also thanks for the training Bootcamp.
#bug

**Comment by harshnambiar** [comment]
Thanks. We will update next iteration of the Bootcamp and so on :)
